import { Selector } from 'testcafe';

fixture `Frontend Tests`
    .page `http://localhost:5000`;  // Ensure this matches your Flask app URL

test('Check index page content and form submission', async t => {
    const heading = Selector('h1');
    const subheading = Selector('h2');
    const emailInput = Selector('#to');
    const subjectInput = Selector('#subject');
    const messageInput = Selector('#message');
    const submitButton = Selector('input[type="submit"]');
    const messageContainer = Selector('#messageContainer');

    // Check the headings are correct
    await t
        .expect(heading.innerText).eql('Send Email')
        .expect(subheading.innerText).eql('Onzecord');

    // Fill out the form
    await t
        .typeText(emailInput, 'gallo.noah@gmail.com')
        .typeText(subjectInput, 'Testcafé frontend testing')
        .typeText(messageInput, 'This is a test message generated by Testcafé')
        .click(submitButton);

    // Wait for the response
    await t.expect(messageContainer.innerText).contains('Email sent successfully.', { timeout: 5000 });
});
