name: CI Pipeline

on:
  push:
    branches-ignore:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r mail_microservice/requirements.txt
    - name: Run unit tests
      run: |
        cd mail_microservice
        python -m unittest discover

  build-and-scan:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Google Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - name: Build Docker image
      run: docker build -t europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest mail_microservice
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest
    - name: Push Docker image to Google Container Registry
      if: success()
      run: docker push europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest

  e2e-tests:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Google Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - name: Pull and run flask service container
      run: |
        docker pull europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest
        docker run -d --name flask -p 5000:5000 europe-west3-docker.pkg.dev/onzecord-416813/onzecord-repo/onzecord-mail:latest
    - name: Wait for flask to be ready
      run: |
        for i in {1..30}; do
          if curl --fail http://localhost:5000; then
            exit 0
          fi
          sleep 2
        done
        echo "Flask did not become ready in time"
        exit 1
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install TestCafe
      run: npm install -g testcafe
    - name: Run TestCafe tests
      run: testcafe chrome:headless test_frontend.js